# Generated by Django 3.2.6 on 2021-08-06 06:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_sname', models.CharField(max_length=80, verbose_name='Фамилия')),
                ('fio_name', models.CharField(max_length=80, verbose_name='Имя')),
                ('fio_lname', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('dolznost', models.CharField(choices=[('rn', 'Руководитель направления'), ('vi', 'Ведущий инженер'), ('1к', 'Инженер 1-й категории')], max_length=3, null=True, verbose_name='Должность')),
                ('napravlenie', models.CharField(choices=[('tee', 'Транспорт электроэнергии'), ('krp', 'Контроль режимов потребления'), ('ptp', 'Подготовка технических приложений к договорам энергоснабжения')], max_length=3, null=True, verbose_name='Направление')),
                ('cont_tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', unique=True, verbose_name='Телефон')),
                ('id_telegramm', models.IntegerField(blank=True, null=True, verbose_name='ID в телеграмме')),
            ],
        ),
    ]
