# Generated by Django 3.2.6 on 2021-08-06 11:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mytbot', '0002_alter_people_dolznost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='napravlenie',
            field=models.CharField(blank=True, choices=[('tee', 'Транспорт электроэнергии'), ('krp', 'Контроль режимов потребления'), ('ptp', 'Подготовка технических приложений к договорам энергоснабжения')], max_length=3, null=True, verbose_name='Направление'),
        ),
        migrations.CreateModel(
            name='Tempa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(null=True, verbose_name='Температура')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='s_name', to='mytbot.people', verbose_name='Сотрудник')),
            ],
        ),
    ]
