# Generated by Django 3.2.6 on 2023-05-07 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_proverki_ii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tu', models.CharField(max_length=10, verbose_name='ID ТУ')),
                ('num_pu', models.CharField(max_length=64, verbose_name='Номер ПУ')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Mpri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tu', models.CharField(max_length=10, verbose_name='ID ТУ')),
                ('num_pu', models.CharField(max_length=64, verbose_name='Номер ПУ')),
                ('mpri', models.IntegerField(verbose_name='Межпроверочный интервал, дней')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True, verbose_name='МПРИ активен')),
                ('neproveryat', models.BooleanField(default=False, verbose_name='Не проверять')),
            ],
        ),
        migrations.CreateModel(
            name='Tochki_dla_proverki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tu', models.CharField(max_length=10, verbose_name='ID ТУ')),
                ('num_pu', models.CharField(max_length=64, verbose_name='Номер ПУ')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True, verbose_name='Точка активна')),
            ],
        ),
    ]
